
#[CONFIGMAP-SECRET]
#1_utl-capadb-service_[ConfigMap-Secret].yml

apiVersion: v1
kind: ConfigMap
metadata:
  name: utl-capadb
  namespace: default
data:
  #-------------------------------------------------------------------#
  #--------------- CONFIGURACION PROPERTIES [utl-capadb] -------------#
  #-------------------------------------------------------------------#
  #IMPORTANTE: 'oracle-external-ip' es un 'ENDPOINT'.
  application.properties: |-
    grupoconfig01.nombres=CESAR GUERRA
    grupoconfig01.dni=41816133
    propiedades.config.valor_01=JAVAMAN
    propiedades.config.valor_02=MAKTUP
    ingress.dns.employee=http://capacitacion.microservicios.employee
    ingress.dns.department=http://capacitacion.microservicios.department
    ingress.dns.organization=http://capacitacion.microservicios.organization
    ingress.dns.utlcapadb=http://capacitacion.microservicios.utlcapadb
    spring.datasource.jdbc-url=jdbc:oracle:thin:@oracle-external-ip:1521:XE 
    spring.datasource.username=cguerra
    spring.datasource.password=12345678
    spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

---

apiVersion: v1
kind: Secret
metadata:
  name: eutl-capadb-secret
  namespace: default
  #-------------------------------------------------------------------#
  #---------------------- CONFIGURACION SECRETs ----------------------#
  #--------- Formato BASE64 (https://www.base64encode.net/) ----------#
  #-------------------------------------------------------------------#
data:
  BOOTADMIN_USUARIO: YWRtaW4=
  BOOTADMIN_PASSWORD: YWRtaW4=

