
#[CONFIGMAP-SECRET]
#1_utl-capadb-service_[ConfigMap-Secret].yml

apiVersion: v1
kind: ConfigMap
metadata:
  name: utl-capadb
  namespace: default
  labels:
    app: microservicio-utl-capadb-service
    role: backend
    stage: production
    version: v1.0.0
data:
  #-------------------------------------------------------------------#
  #--------------- CONFIGURACION PROPERTIES [utl-capadb] -------------#
  #-------------------------------------------------------------------# 
  application.properties: |-
    grupoconfig01.nombres=CESAR GUERRA
    grupoconfig01.dni=41816133
    propiedades.config.valor_01=JAVAMAN
    propiedades.config.valor_02=MAKTUP
    ingress.dns.employee=http://capacitacion.microservicios.employee
    ingress.dns.department=http://capacitacion.microservicios.department
    ingress.dns.organization=http://capacitacion.microservicios.organization
    ingress.dns.utlcapadb=http://capacitacion.microservicios.utlcapadb
    spring.datasource.jdbc-url=jdbc:oracle:thin:@oracle-external-ip:1521:XE
    spring.datasource.username=${ORACLE_USUARIO}
    spring.datasource.password=${ORACLE_PASSWORD}
    spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
    
---

apiVersion: v1
kind: Secret
metadata:
  name: utl-capadb-secret
  namespace: default
  labels:
    app: microservicio-utl-capadb-service
    role: backend
    stage: production
    version: v1.0.0
  #-------------------------------------------------------------------#
  #---------------------- CONFIGURACION SECRETs ----------------------#
  #--------- Formato BASE64 (https://www.base64encode.net/) ----------#
  #-------------------------------------------------------------------#
data:
  BOOTADMIN_USUARIO: YWRtaW4=
  BOOTADMIN_PASSWORD: YWRtaW4=
  ORACLE_USUARIO: Y2d1ZXJyYQ==
  ORACLE_PASSWORD: MTIzNDU2Nzg=
  
  