
#[DEPLOYMENT-SERVICE]
#2_utl-capadb-service_[Deployment-Service].yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: utl-capadb-service
  namespace: default
  labels:
    app: microservicio-utl-capadb-service
    role: backend
    stage: production
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-utl-capadb-service
      version: v1.0.0  
  template:
    metadata:
      labels:
        app: microservicio-utl-capadb-service
        version: v1.0.0
    spec:
      containers:                  
        - name: microservicio-utl-capadb-service
          image: maktup/utl-capadb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          #IMPORTANTE: Si NO se configura [CPU/RAM] NO funcionara el: 'AUTOSCALING'.     
          resources:
            limits:
              cpu: 500m
          env:
          #CONFIGURACION DE 'SECRETs':
          - name: DUMMY_VARIABLE
            value: javaman
            
          - name: BOOTADMIN_USUARIO
            valueFrom:
              secretKeyRef:
                key: BOOTADMIN_PASSWORD
                name: utl-capadb-secret
            
          - name: BOOTADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: BOOTADMIN_PASSWORD
                name: utl-capadb-secret
                
          - name: ORACLE_USUARIO
            valueFrom:
              secretKeyRef:
                key: ORACLE_USUARIO
                name: utl-capadb-secret
            
          - name: ORACLE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ORACLE_PASSWORD
                name: utl-capadb-secret 
          #--------------------------#  
          volumeMounts:
          - mountPath: /app/log
            name: volumen-logs 
      volumes:
        - name: volumen-logs 
          persistentVolumeClaim:
            #claimName: microservicio-utl-capadb-pvc
            #APUNTAR al VOLUMEN de 'FILEBEAT'
            claimName: filebeat-pvc
          #--------------------------#      
                              
---

apiVersion: v1
kind: Service
metadata:
  name: utl-capadb-service
  namespace: default
  labels:
    app: microservicio-utl-capadb-service
    role: backend
    stage: production
spec: 
  ports:
    - name: http
      port: 8080
  selector:
    app: microservicio-utl-capadb-service
    version: v1.0.0
  type: NodePort

 